name: Friends-MSG-Toggle-For-PAF
version: ${project.version}
author: Simonsator
depends: [PartyAndFriends]
main: de.simonsator.partyandfriends.friendtoggle.FTMain
description: An add-on for party and friends which adds the command /friend toggle
